# Generated by Django 3.2.8 on 2022-03-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=255, unique=True, verbose_name='ツイートID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザーID')),
                ('user_name', models.CharField(max_length=225, verbose_name='ユーザー名')),
                ('text', models.TextField(blank=True, null=True, verbose_name='ツイート内容')),
                ('favorite', models.PositiveIntegerField(verbose_name='いいね数')),
                ('retweet', models.PositiveIntegerField(verbose_name='リツイート数')),
                ('created_at', models.DateTimeField(verbose_name='ツイート日時')),
                ('loaded_at', models.DateTimeField(auto_now_add=True, verbose_name='データ取得日')),
            ],
        ),
    ]
