# Generated by Django 3.2.8 on 2022-03-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweepy_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True, verbose_name='キーワード')),
            ],
        ),
    ]
