# Generated by Django 3.2.8 on 2022-03-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweepy_test', '0003_auto_20220310_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='keyword',
            field=models.CharField(max_length=255, verbose_name='検索キーワード'),
        ),
    ]
