# Generated by Django 3.2.8 on 2022-03-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweepy_test', '0004_alter_tweets_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetkeyword',
            name='keyword',
            field=models.CharField(max_length=190, unique=True, verbose_name='キーワード'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='keyword',
            field=models.CharField(max_length=190, verbose_name='検索キーワード'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='tweet_id',
            field=models.CharField(max_length=190, verbose_name='ツイートID'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='user_id',
            field=models.CharField(max_length=190, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='user_name',
            field=models.CharField(max_length=190, verbose_name='ユーザー名'),
        ),
    ]
