# Generated by Django 3.2.8 on 2022-03-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweepy_test', '0005_auto_20220313_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetkeyword',
            name='keyword',
            field=models.CharField(max_length=190, verbose_name='キーワード'),
        ),
    ]
